name: atmaCup11
channels:
  - pytorch
  - conda-forge
  - default
  - anaconda
  - plotly
dependencies:
  - cudatoolkit=10.2
  - python=3.8
  - pytorch
  - torchvision
  - torchaudio
  - visdom
  - jupyter
  - numpy
  - scipy
  - matplotlib
  - matplotlib-venn # nykerさんのcourse1
  - scikit-image
  - tensorboard # vscodeのtensorboard拡張
  - tensorboardx
  - dill
  - dominate # HTMLでいい感じに見る奴作るの
  - configargparse
  - gensim # word2vec
  - tqdm
  - pandas
  - opencv # Lab色空間ヒストグラムを特徴量にしたい
  - seaborn # nykerさんの可視化
  - hydra-core # lighlyのdependencies
  - pytorch-lightning # lighlyのdependencies
  - python-levenshtein # gensim.similarities.levenshtein submoduleがない警告を無くす
  - kornia
  - debugpy
  - ruby # tmuxinator
  - tmux # tmuxinator
  - line_profiler
  - pudb
  - plotly
  - pynvim
  - mypy
  - pylint
  - yapf
  - flake8
  - black
  - ipykernel
  - pip
  - pip:
    - better_exceptions
    - icecream
    - lightly
    - torchsummary
    - python-vivid #nykerさんの便利ツールセット
    - grad-cam # nyker講座#2
    - ttach #grad-camの依存
    - torch-tb-profiler #
    - --pre --extra-index https://pypi.anaconda.org/scipy-wheels-nightly/simple
    - scikit-learn
# vim:ts=2 sw=2
