niter: 5
save_epoch_freq: 1
no_html: true
save_steps: true
save_latest_freq: 20480
dataroot: /data/natsuki/dataset_atmaCup11
checkpoints_dir: /data/natsuki/dataset_atmaCup11/checkpoints
#gpu_ids: 0,1,2,3,4,5,6,7
gpu_ids: 0 #もしかしてデータパラレルだと遅いんじゃねぇの？
#batchSize: 2048 # 256*8gpu
batchSize: 256 # 256*8gpu